name: Setup and Auth gCloud CLI
description: Setup and authenticate gCloud CLI using Workload Identity Federation

inputs:
  gcp-project-id:
    description: GCP Project ID
    required: true
    type: string
  wl-id-provider:
    description: Workload Identity Provider
    required: true
    type: string
  service-account:
    description: GHA Service Account Email
    required: true
    type: string

outputs:

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.wl-id-provider }}
        service_account: ${{ inputs.service-account }}
        project_id: ${{ inputs.gcp-project-id }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v3
      with:
        install_components: beta
